#!/bin/sh
# Author: Jens Getreu

package () {

OutDirName="./doc/build/dist/"
mkdir -p "$OutDirName"
ZipBaseName=$(basename "$2" ".zip")
ZipFileName="$OutDirName/$ZipBaseName.zip"
DownloadDir="$OutDirName/../html/_downloads/"
mkdir -p "$DownloadDir"



zip -r "$ZipFileName" "$1" 
cd "$DownloadDir"
ln -sf "../../dist/$ZipBaseName.zip" .
}


package "dist" "asciiart-hangman-for-kids.zip"
