#!/bin/sh
# Author: Jens Getreu

# Todo document rustup preparation for the Windows target

cargo build --release
cp ./target/release/hangman ./dist/bin/

cargo build --release --target=x86_64-pc-windows-gnu
cp ./target/x86_64-pc-windows-gnu/release/hangman.exe ./dist/bin/

cargo clean
