#!/bin/bash
# Author: Jens Getreu

# apt install pandoc asciidoctor-fopub
FOPUB_PATH="/usr/local/java-deployment/asciidoctor-fopub/bin/"

render () {
    ### parse args

    #set -x
    InPath="$1"
    InFile="${InPath##*/}"
    InBase="${InFile%.*}"
    InDir="${InPath%/*}"
    if [ "$InDir" = "$InPath" ] ; then
        InDir="."
    fi

    OutPath="$2"
    OutFile="${OutPath##*/}"
    OutBase="${OutFile%.*}"
    OutDir="${OutPath%/*}"
    if [ "$OutDir" = "$OutPath" ] ; then
        OutDir="."
    fi


    ### Prepare

    HtmlPath="$OutDir/$OutBase.html"
    HtmlFile="${XmlPath##*/}"

    mkdir -p "$OutDir"

    ### Generate Html
    
    # this is only needed for html and xml output
    cp -r  "$InDir/images/" "$OutDir"
    cp "$InPath" "$OutDir"
    cd "$OutDir"
    asciidoctor -b html5 -a data-uri! "$InFile"

    rm "$InFile"
}



### Main
# usage: 
# render FILE [FILE]
# render report.adoc ./rendition/report.html

if [[ -n "${2/[ ]*\n/}" ]] ; then
        OutPath="$2"
else
        OutPath="${1%.*}.pdf" # $2 is empty
fi
render "$1" "$OutPath" 


