#!/bin/sh

rustup update
### Better comment it out here, because in `ascii-hangman-backend/Cargo.toml`
### is a dependency that need manual adjustment.
# cargo upgrade --all
cargo update

rm -r ../target
rm -r ../doc/build

cd ..
grep -F -v -e [lib] -e cdylib Cargo.toml  > Cargo.toml.tmp && mv Cargo.toml.tmp Cargo.toml
