#!/bin/sh
#set -x
cd ..
find target -mindepth 2 -not -path "*/release/ascii-hangman" \
                        -not -path "*/release/ascii-hangman.exe" \
                        -not -path "*/debian" \
                        -not -path "*/debian/ascii-hangman*.deb" \
                        -not -path "*/release/*.md" \
                        -not -path "*/release" \
                        -not -path "target/doc*"  \
                        -exec rm -r {} \;

rm -r target/debug
rm -r target/wasm32-unknown-unknown
rm -r target/release
rm -r target/rls
rm target/.rustc_info.json
rm -r doc/build/pkg

