#!/bin/sh
BUILD_DIR="./doc/build/"
WWW_DIR="$BUILD_DIR/html/web-app/"

set -x
cd ../
cp ./static/* "$WWW_DIR"
python3 -m http.server --directory "$WWW_DIR"

### Alternatively install miniverve.
# cargo +nightly install miniserve

### And run it.
# miniserve ./static --index index.html
